### PR TITLE
Promisify some sharp calls

### PR DESCRIPTION
**Pull request by rejas**
While tinkering around #65 I noticed that some calls to the sharp-library could be used with promises.
Makes some cleaner code.
~~Also fixed some deprecation warning with latest sharp lib~~ (sharp deprecations will be fixed in a different PR
Comments? Improvement ideas?

### CODE REVIEW

**Comment by rejas** [comment]
Hi @mahnunchik any chance to get thi smerged? Or dont you have time for this plugin anymore?

**Comment by mahnunchik** [comment]
@rejas hi, is it breaking change?

**Comment by rejas** [comment]
No, no breaking changes in there which I could think of.

**Comment by mahnunchik** [comment]
Done!

**Pull request merged**
