### PR TITLE
Added the max option

### PR DESCRIPTION
**Pull request by subblue**
Useful to resize to max width or height values while keeping the aspect
ratio of the original image.

### CODE REVIEW

**Comment by mahnunchik** [comment]
Hi @subblue 

Thank you for implementing one more option of `sharp`!

I think `max` option should be set to `false` by default to preserve the behavior for config without using `max` option.

**Comment by subblue** [comment]
I did originally think this too as it makes sense from a purely programatic point of view. However, from a users point of view expecting sensible defaults you are more likely to want to retain the aspect ratio when resizing to fit within a given width and height. The default setting of ```max: true``` would give the most expected result, without first getting a distorted resize and then wondering how to fix it, which is what happened to me ;)

If you think it is better to require the user to explicitly set the ```max: true``` option then I'll happily update the pull request.

**Comment by mahnunchik** [comment]
My point of view is that we could not predict the user's wishes. In both cases, we will make someone set `max: truth` and someone else set `max: false`.

So I think it's better to set `max: false` by dafault by the following reasons:
* not to break existing behavior
* follow the behavior of the [main library](https://github.com/lovell/sharp#max) (it is more important)

**Comment by subblue** [comment]
Good points. Here you go :)

**Comment by mahnunchik** [comment]
@subblue Thanks!

[1.0.7](https://github.com/mahnunchik/gulp-responsive/releases/tag/1.0.7)

**Pull request merged**
