### PR TITLE
Expose more underlying sharp methods

### PR DESCRIPTION
**Pull request by PizzaBrandon**
I need to do a little more image transformation (transparent PNG to colored-background JPEG, for example) than is currently exposed through the plugin. This PR adds the methods I'm using.

### CODE REVIEW

**Comment by mahnunchik** [comment]
Hi @PizzaBrandon,

Thank you for your interest in improving `gulp-responsive`! :+1: 

I think the following changes are necessary:
* expand the default config by new options https://github.com/PizzaBrandon/gulp-responsive/blob/master/lib/config.js#L60
* add a check to the `flatten` option to avoid setting `true` by default https://github.com/PizzaBrandon/gulp-responsive/blob/master/lib/sharp.js#L55
* add some kind of rename management to allow using the following config:
```js
{
  'logo.png': {
    jpeg: true
  }
}
```
and get `logo.jpg` in output if `rename` option was not specified

**Comment by PizzaBrandon** [comment]
Thanks. I'll look into this soon.

**Comment by mahnunchik** [comment]
@PizzaBrandon 
I think format/rename options are most difficult part of this PR, so PR can be divided into two parts:
* background, embed, max, flatten - almost done
* and output format option

it allow us to add new features as soon as possible :wink:

**Comment by PizzaBrandon** [comment]
Closing since it seems I won't be able to get back to this for a while still.

**Pull request closed without merging**
