### PR TITLE
Upgrade sharp to @latest

### PR DESCRIPTION
**Pull request by khteh**
https://github.com/mahnunchik/gulp-responsive/issues/124

### CODE REVIEW

**Comment by milottit** [comment]
Actually the last sharp version is 0.23

**Comment by milottit** [comment]
Would it be possible to update it because I get the same error with node v12?

**Comment by milottit** [comment]
Would it be possible to update it because I get the same error with node v12?

**Comment by takueof** [comment]
@mahnunchik (Cc: @milottit)
Hi, I'm having trouble with the same symptoms as @khteh.
Is it possible to merge after changing this PR to v0.23.0...?

**Comment by StarpTech** [comment]
Fixed by https://github.com/mahnunchik/gulp-responsive/pull/129

**Pull request closed without merging**
